        Integer         kcompMax,
     *                  kolMax,
     *                  ncodMax,
     *                  natmMax,
     *                  nwavMax,
     *                  nedgMax,
     *                  nabcMax,
     *                  nedgTb,
     *                  maxX0hWarnLines
c       Parameter       (kcompMax =  10)		! before 6/2024
c       Parameter       (kolMax   =  32)		! before 6/2024
        Parameter       (kcompMax =  20)
        Parameter       (kolMax   = 200)
        Parameter       (ncodMax  = 400)
        Parameter       (natmMax  = 100)
        Parameter       (nwavMax  =  50)
        Parameter       (nedgMax  =  16)
        Parameter       (nabcMax  =  11)
        Parameter       (nedgTb   =   5)
        Parameter       (maxX0hWarnLines = 20)
