        Integer         kcompMax,
     *                  kolMax,
     *                  ncodMax,
     *                  natmMax,
     *                  nwavMax,
     *                  nedgMax,
     *                  nabcMax,
     *                  nedgTb,
     *                  maxX0hWarnLines
        Parameter       (kcompMax = 10)
        Parameter       (kolMax   = 32)
        Parameter       (ncodMax  =200)
        Parameter       (natmMax  =100)
        Parameter       (nwavMax  = 50)
        Parameter       (nedgMax  = 16)
        Parameter       (nabcMax  = 11)
        Parameter       (nedgTb   = 5)
        Parameter       (maxX0hWarnLines = 20)
